import type { LoanScenario, ScpiDatabaseEntry, SimulationInput } from '../types/simulation'

export const MONTHS_IN_YEAR = 12
export const SOCIAL_CONTRIBUTIONS_RATE = 0.186

export const INPUT_LIMITS = {
  downPaymentAmount: { min: 0, max: 10000000 },
  loanDurationYears: { min: 1, max: 30 },
  loanAnnualRate: { min: 0, max: 0.15 },
  loanAnnualInsuranceRate: { min: 0, max: 0.03 },
  otherInitialExpenses: { min: 0, max: 1000000 },
  enjoymentDelayMonths: { min: 0, max: 24 },
  distributionRate: { min: 0, max: 0.15 },
  subscriptionFeeRate: { min: 0, max: 0.25 },
  investmentAmount: { min: 1000, max: 10000000 },
  taxBracketRate: { min: 0, max: 0.45 },
  revenueInFranceRate: { min: 0, max: 1 },
  foreignTaxRate: { min: 0, max: 1 },
  annualRevaluationRate: { min: -0.05, max: 0.08 },
  horizonYears: { min: 1, max: 40 },
} as const

export const DEFAULT_SIMULATION_INPUT: SimulationInput = {
  useLoan: true,
  downPaymentAmount: 50000,
  loanDurationYears: 20,
  loanAnnualRate: 0.040,
  loanAnnualInsuranceRate: 0.0006,
  otherInitialExpenses: 5110,
  enjoymentDelayMonths: 6,
  distributionRate: 0.060,
  subscriptionFeeRate: 0.1,
  investmentAmount: 200000,
  taxBracketRate: 0.41,
  revenueInFranceRate: 0.179,
  foreignTaxRate: 0.20,
  annualRevaluationRate: 0.003,
  horizonYears: 30,
}

export const DEFAULT_LOAN_SCENARIOS: LoanScenario[] = [
  {
    id: "scenario-court",
    name: "Court",
    editable: true,
    downPaymentAmount: 45000,
    loanDurationYears: 15,
    loanAnnualRate: 0.0355,
    loanAnnualInsuranceRate: 0.0015,
  },
  {
    id: "scenario-base",
    name: "Moyen",
    editable: true,
    downPaymentAmount: 35000,
    loanDurationYears: 20,
    loanAnnualRate: 0.040,
    loanAnnualInsuranceRate: 0.002,
  },
  {
    id: "scenario-long",
    name: "Long",
    editable: true,
    downPaymentAmount: 20000,
    loanDurationYears: 25,
    loanAnnualRate: 0.043,
    loanAnnualInsuranceRate: 0.003,
  },
];

export const DEFAULT_SCPI_DATABASE: ScpiDatabaseEntry[] = [
  {
    id: 'scpi-corum-origin',
    name: 'Corum Origin',
    organization: 'Corum',
    enjoymentDelayMonths: 5,
    subscriptionFeeRate: 0.1196,
    managementFeeRate: 0.132,
    distributionFrequency: 'monthly',
    franceShareRate: 0.05,
    sharePurchasePrice: 1135,
    distributionRate: 0.065,
    pgaRate: 0.065,
    irr10Years: 0.0675,
    creationYear: 2012,
  },
  {
    id: 'scpi-sofidynamic',
    name: 'SOFIDYNAMIC',
    organization: 'Sofidy',
    enjoymentDelayMonths: 5,
    subscriptionFeeRate: 0.02,
    managementFeeRate: 0.144,
    distributionFrequency: 'quarterly',
    franceShareRate: 0.53,
    sharePurchasePrice: 320,
    distributionRate: 0.0904,
    pgaRate: 0.1404,
    irr10Years: 0,
    creationYear: 2023,
  },
  {
    id: 'scpi-transitions-europe',
    name: 'Transitions Europe',
    organization: 'ARKEA REIM',
    enjoymentDelayMonths: 5,
    subscriptionFeeRate: 0.1,
    managementFeeRate: 0.1,
    distributionFrequency: 'quarterly',
    franceShareRate: 0,
    sharePurchasePrice: 202,
    distributionRate: 0.076,
    pgaRate: 0.086,
    irr10Years: 0,
    creationYear: 2022,
  },
  {
    id: 'scpi-iroko-zen',
    name: 'Iroko Zen',
    organization: 'Iroko',
    enjoymentDelayMonths: 4,
    subscriptionFeeRate: 0,
    managementFeeRate: 0.144,
    distributionFrequency: 'monthly',
    franceShareRate: 0.29,
    sharePurchasePrice: 204,
    distributionRate: 0.0714,
    pgaRate: 0.0813,
    irr10Years: 0.06,
    creationYear: 2020,
  },
  {
    id: 'scpi-epargne-pierre-europe',
    name: 'Epargne Pierre Europe',
    organization: 'Atland Voisin',
    enjoymentDelayMonths: 5,
    subscriptionFeeRate: 0.1,
    managementFeeRate: 0.12,
    distributionFrequency: 'quarterly',
    franceShareRate: 0,
    sharePurchasePrice: 200,
    distributionRate: 0.0675,
    pgaRate: 0.0675,
    irr10Years: 0.055,
    creationYear: 2022,
  },
  {
    id: 'scpi-alta-convictions',
    name: 'Alta Convictions',
    organization: 'Altarea',
    enjoymentDelayMonths: 3,
    subscriptionFeeRate: 0.1014,
    managementFeeRate: 0.1374,
    distributionFrequency: 'monthly',
    franceShareRate: 0.92,
    sharePurchasePrice: 308,
    distributionRate: 0.0657,
    pgaRate: 0.0755,
    irr10Years: 0,
    creationYear: 2023,
  },
  {
    id: 'scpi-comete',
    name: 'Comete',
    organization: 'Alderan',
    enjoymentDelayMonths: 5,
    subscriptionFeeRate: 0.1,
    managementFeeRate: 0.132,
    distributionFrequency: 'monthly',
    franceShareRate: 0,
    sharePurchasePrice: 250,
    distributionRate: 0.09,
    pgaRate: 0.09,
    irr10Years: 0,
    creationYear: 2023,
  },
]
